### PR TITLE
Fix deprecation warning in gradle 7.4

### PR DESCRIPTION
**Pull request by jpenilla**
Tested to fix deprecation warning & still work on older Gradle

### CODE REVIEW

**Comment by jamierocks** [comment]
This would require a new major version of licenser, but that seems fine to me :)

**Comment by jpenilla** [comment]
Went ahead and bumped the version to 0.7.0

**Comment by jamierocks** [comment]
I meant merely as a comment for what version that would release into, just to remind myself when merging :)

**Comment by zml2008** [comment]
I believe just adding use of an annotation won't cause execution failures -- you should be able to test that using the fuctional test suite though?

**Comment by jpenilla** [comment]
I just ran the functional tests and they still pass with this change. I had assumed there would be an error when Gradle tries reading the annotations, but you're right that there isn't.

**Comment by jpenilla** [comment]
I have confirmed in a test project that licenser still works in Gradle 6.7 with this change. Is there anything else I can do to help get this merged?

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Looks good to me, is there any chance of getting this released? Some of my gradle builds are ran with deprecations set to fail, so this is a bit of a blocking issue for me.

Thanks 👍

**Comment by CDAGaming** [comment]
Any updates? Followed modmuss' footsteps and swapped for spotless, but I'd really love to continue using this.

**Pull request closed without merging**
