### PR TITLE
Add option to skip existing headers in files

### PR DESCRIPTION
**Pull request by joschi**
The new `skipExistingHeaders` configuration setting allows to skip over files that already have some header conforming to the configured header style, which might not be the one specified in the header parameter.

### CODE REVIEW

**Comment by joschi** [comment]
@jamierocks @Minecrell Any chance to publish this PR and the PRs you've already merged since licenser 0.5.0 in a new release?

**Comment by jamierocks** [comment]
@joschi I apologise that I've not gotten back to you sooner - I would like to round up your great work into a 0.5.1 release shortly.

As far as this PR goes, I'll discuss it with @Minecrell. Though it would be handy if you could elaborate on the usecase of this over excluding source files?

**Comment by joschi** [comment]
@jamierocks Thanks for checking!

The use case is adding the licenser plugin to a project with existing source files and their history.

Some might have been imported from other code bases and already have a license header which shouldn't be touched. If the number of individual source files with preexisting license headers is high enough, it's not viable to add each of them via `exclude`.

**Comment by jamierocks** [comment]
@joschi Thanks for the swift reply there!

Having discussed the change with @Minecrell, I see no reason not to bring this in. I'll pull it down in the morning, do the usual pre-merge verifications and get this in :)

**Pull request merged**
